### ISSUE TITLE
상징 생성시 카메라 권한 버그

### ISSUE THREAD

**Issue by paul2126** [snuhcs-course/swpp-2023-project-team-6#103]
상징 생성 페이지에서 사진 촬영을 선택할 경우 권한 설정 메세지가 뜨는데 취소를 선택한 다음, 다시 사진 촬영을 선택하면 권한 설정 메세지가 안 뜨고 바로 설정에서 권한을 허용해달라는 메세지가 뜹니다. 
설정에서 권한을 줄 수 있기 때문에 큰 문제는 아닌데 다시 메세지를 띄우는 것이 더 좋아보입니다.

**Comment by paul2126** [comment]
찾아보니까 안드로이드 자체에서 2번 권한을 부여하지 않으면 그 다음부터는 안 물어보도록 되어있다고 하네요. 그럴 경우에는 바로 유저한테 안드로이드 앱 설정으로 보내서 권한 부여하도록 할 수 있긴 한데 그러면 저희 테스트가 좀 바뀌어야 할 것 같아서 그냥 두는 것 어떨까요? 
좋은 코드는 아니긴 하지만... 그래도 어떻게 권한 부여할 수 있는지 설명이 나와서 큰 문제는 없을 것 같아요

**Comment by sukchan-0811** [comment]
> 찾아보니까 안드로이드 자체에서 2번 권한을 부여하지 않으면 그 다음부터는 안 물어보도록 되어있다고 하네요. 그럴 경우에는 바로 유저한테 안드로이드 앱 설정으로 보내서 권한 부여하도록 할 수 있긴 한데 그러면 저희 테스트가 좀 바뀌어야 할 것 같아서 그냥 두는 것 어떨까요? 좋은 코드는 아니긴 하지만... 그래도 어떻게 권한 부여할 수 있는지 설명이 나와서 큰 문제는 없을 것 같아요

저는 그대로 둬도 된다고 생각합니다...! 하핫,,,
