### ISSUE TITLE
상징 선택 시 UI 이슈

### ISSUE THREAD

**Issue by yjeong-k** [snuhcs-course/swpp-2023-project-team-6#115]
<우선순위가 낮은 usability 관련 이슈입니다>

상징 선택 페이지에서, 리스트를 쭉 내려서 밑에 있는 상징을 선택하면
지금은 상징 선택 후에도 리스트의 아래에 그대로 위치해 있어서
추천받은 상징을 보려면 위로 다시 올려야 합니다
추천받은 상징을 1순위부터 바로 보기 위해서
어떤 상징을 선택했을 때 리스트 최상단으로 자동으로 올라가면 좋을 것 같습니다!

에러는 아니다보니 시간이 되신다면 다루고 그렇지 않으면 그냥 둬도 될 것 같습니다..

**Comment by paul2126** [comment]
수정해서 pr 올렸습니다
hotfix/db-init이 머지가 될꺼라 거기서 브랜치 파서 작업했습니다!

**Comment by yjeong-k** [comment]
넘감사합니다!!
