### ISSUE TITLE
백업, 로그아웃 후 재로그인 시 추가한 상징, 즐겨찾기 날라가는 이슈

### ISSUE THREAD

**Issue by prime2do** [snuhcs-course/swpp-2023-project-team-6#120]
제가 제 이메일로 계정 새로 만들어서 이것저것 해봤는데요,
상징을 새로 만들고, 즐겨찾기도 몇 개 해둔 후에 서버에 백업하기를 누르고 성공 메시지 뜨는 것까지 확인했는데도
로그아웃 후 다시 로그인하면 제가 추가한 상징과 즐겨찾기 목록이 날아가 있습니다.
어떨 때는 만든 상징은 남아있고 즐겨찾기만 날아가고, 어떨 때는 둘 다 날아갑니다.
그리고 그거랑 관련된 문제인지는 모르겠으나 백업이 몇분동안 계속 로딩만 된다든지, 앱이 튕기고 clear cache를 하라는 등의 상황도 발생하는 것을 확인했습니다.
새 계정 만들어서 시도해보고 혹시 다른 기기에서도 문제가 발생하나 확인해봐야 할 것 같습니다.

**Comment by prime2do** [comment]
방금 또 해보니
만든 상징을 즐겨찾기에 추가하고 기본 상징도 즐겨찾기에 추가했을 때, 만든 상징은 즐겨찾기에 남아있으나 기본 상징은 즐겨찾기에서 날아가는 경우가 있었습니다

**Comment by paul2126** [comment]
혹시 해당 버그 터질때 로그 남아있을까요?

**Comment by prime2do** [comment]
![infinite loading](https://github.com/snuhcs-course/swpp-2023-project-team-6/assets/144990005/c5b51c06-4490-45ba-8b3f-68f869da141a)
이거는 백업 도중 무한로딩 걸릴 때 로그입니다. 저거 이전에 다른 것들은 다 200 ok 뜨는데 웨이트테이블만 저렇게 뜨는거 같아요

**Comment by prime2do** [comment]
![favorite gone](https://github.com/snuhcs-course/swpp-2023-project-team-6/assets/144990005/29ba411d-4a88-455d-a7b5-ae5d0a86b8f4)
이거는 아까 위의 상태에서 백업 안 하고 로그아웃 후 재로그인 했을 때 favorite이 가져와지지 않는 부분 로그입니다. 로그 빨간 부분 위에 보면 아시겠지만 내가 만든 상징은 잘 가져와집니다.
