### ISSUE TITLE
UI/UX 개선해야 할 사항

### ISSUE THREAD

**Issue by sukchan-0811** [snuhcs-course/swpp-2023-project-team-6#24]
에뮬레이터가 아닌 디바이스 환경에서 실제로 사용해보면서 개선이 필요하다고 느낀 UI/UX 관련 사항들입니다.
가능하다면 Heuristic Evaluation 전까지 작업하면서 그때그때 반영할 수 있으면 하는 게 좋을 것 같아요.

**앱 전반**
- [ ] 앱 처음에 켜면 Landing Screen 전에 잠깐 뜨는 흰 바탕 화면의 배경색을 Landing Screen 배경색과 맞추면 좋을 것 같아요
- [x] 시스템 내비게이션 바로 인해서 앱의 밑부분이 전체적으로 조금씩 잘립니다. Bottom Padding을 모든 스크린에 대해서 일일이 넣는 것보다는 더 깔끔한 해결방법이 있을 것 같은데 찾아봐야 할 것 같아요
- [x] 위와 연결된 문제인데, [안드로이드 디자인 패턴](https://designcompass.org/2020/03/01/ios-android-ui-%EB%94%94%EC%9E%90%EC%9D%B8/)에 따르면 안드로이드의 경우에는 시스템 내비게이션 바가 있어서 Top App Bar에 뒤로가기 버튼을 두지 않는 것이 관행이라고 합니다. 이 부분 수정하면 좋을 것 같아요
- [x] **인터넷 연결 안 됐을 때 서버에 요청 보내면 앱이 바로 죽어서 이 부분 에러 처리가 시급합니다**

**인증 관련 화면(로그인/회원가입 등)**
- [x] 인증과 관련된 화면들에서 Top App Bar와 스크린 배경의 색깔이 미묘하게 다른데 이 부분 통일하면 좋을 것 같아요
- [ ] 디바이스에서는 TextFieldUi를 터치해 키보드가 올라왔을 때 버튼의 위치가 자동으로 조정되지 않습니다. 이 때문에 로그인/회원가입 등 할 때 불편할 수 있을 것 같아요
- [x] '비밀번호를 잊으셨나요?' 클릭 후 이메일 입력, 인증번호 발송하려고 할 때 '해당 이메일로 가입된 계정이 없습니다.' 에러가 발생하면 인증번호 발송 버튼도 비활성화하면 좋을 것 같아요
- [x] 회원가입 전 이메일 인증할 때 이메일 입력 후 인증번호 발송 버튼 누르면 몇 초 간 반응이 없어서 버튼을 여러 번 누르게 됩니다. 이 경우에도 버튼을 한번 누르면 처리가 완료될 때까지 버튼을 비활성화하면 좋을 것 같아요

**홈 화면(상징 선택/추가, TTS 페이지 등)**
- [ ] TTS 페이지랑 상징 추가 페이지에 제목, 설명이 조금 불필요하다고 느껴지는 것 같아요 (Top App Bar에 이미 제목이 있습니다)
- [x] TTS 페이지 TextFieldUi 사이즈를 조금 줄여도 괜찮을 것 같습니다
- [x] TTS 페이지에서 아무 텍스트도 입력 안 하고 재생하기 버튼 누르면 '텍스트를 입력해주세요' 에러 메시지를 TextFieldUi 밑에 띄우면 좋을 것 같아요
- [ ] 디스플레이 설정에서 Switch 버튼과 Radio 버튼을 정렬하면 좋을 것 같아요
- [ ] 다크 모드 Switch 버튼이 하는 역할이 조금 애매한 것 같아요 ('지금 다크모드로 변경'인지 아니면 '시스템의 다크모드 설정을 따라감'인지?)
- [ ] 버전 정보에서 'speechbuddy@gmail.com' 왼쪽 텍스트를 '이메일'에서 '개발자 이메일'로 바꾸면 좋을 것 같아요

**Comment by paul2126** [comment]
하단 네비게이션 바에서 자신이 있는 페이지 아이콘을 눌러도 다시 로딩이 됩니다. 안 되게 막을 수 있으면 좋을 것 같아요

**Comment by paul2126** [comment]
[상징 페이지 튀는 문제](https://github.com/snuhcs-course/swpp-2023-project-team-6/pull/53#issuecomment-1822352501)

**Comment by paul2126** [comment]
저희 텍스트 필드 선택했을 때 테두리에 파란색으로 변하는 곳과 초록색으로 변하는 곳 변경해야합니다

**Comment by sukchan-0811** [comment]
> [상징 페이지 튀는 문제](https://github.com/snuhcs-course/swpp-2023-project-team-6/pull/53#issuecomment-1822352501)

상징 페이지가 아니라 설정 페이지 관련 문제 맞나요?

**Comment by paul2126** [comment]
> > [상징 페이지 튀는 문제](https://github.com/snuhcs-course/swpp-2023-project-team-6/pull/53#issuecomment-1822352501)
> 
> 상징 페이지가 아니라 설정 페이지 관련 문제 맞나요?

아 설정 맞아요. 잘못 썼네요.
수정했습니다
