### ISSUE TITLE
유저가 만든 상징의 이미지 불러오기 관련 이슈

### ISSUE THREAD

**Issue by yjeong-k** [snuhcs-course/swpp-2023-project-team-6#31]
현재 구현된 바로는 상징의 이미지를 불러올 때
1) imageUrl이 존재하면(유저가 만든 상징) 그 url에서 이미지를 가져오고(from s3 bucket)
2) 존재하지 않으면(기존 500개 상징) assets/images에서 symbol_{id}.png를 불러오는 것으로 되어있습니다.

따라서 지금은 유저가 인터넷에 연결되어 있지 않으면 자신이 만든 상징 이미지를 불러올 수 없습니다
그래서 석찬님, 승민님과 함께 논의하여 로컬에도 이미지 저장을 따로 하기로 결정했는데
assets는 읽기전용이라 유저가 올린 이미지를 assets/images에 저장할 수가 없더라구요🥲

그래서 찾아보니 앱마다 내부 저장소가 있다고 해서 여기에 이미지를 저장하면 될 거 같은데,
지금은 로컬 상징 이미지를 불러오는 path가 assets로 하드코딩 되어있어서 path에도 수정이 필요할 것 같습니다!

좋은 해결 방안이 있으시면 알려주시면 정말 감사할 것 같고, 추후 윗 내용 수정하도록 하겠습니다🙂

**Comment by sukchan-0811** [comment]
이 이슈 해결된 거 맞나요?

**Comment by yjeong-k** [comment]
앗 넵 해결되었습니다!
