### ISSUE TITLE
설정 백업시 자동 백업 여부 누락

### ISSUE THREAD

**Issue by paul2126** [snuhcs-course/swpp-2023-project-team-6#58]
설정 백업시 자동 백업 여부가 누락되어있어서 나중에 수정 필요합니다

**Comment by sukchan-0811** [comment]
> 설정 백업시 자동 백업 여부가 누락되어있어서 나중에 수정 필요합니다

이 이슈는 해결된 건가요?

**Comment by yjeong-k** [comment]
@paul2126 
@sukchan-0811 
백에서는 auto_backup 저장할 수 있도록 수정하였습니다!
