### ISSUE TITLE
앱 시작시 디스플레이 설정으로 시작하는 경우

### ISSUE THREAD

**Issue by paul2126** [snuhcs-course/swpp-2023-project-team-6#61]
확실한 조건은 모르겠지만 다크모드로 설정해놓으면 앱 시작시 상징 선택이나 tts 화면이 아닌 디스플레이 설정으로 시작하는 경우가 있습니다

**Comment by sukchan-0811** [comment]
이 이슈 해결된 건가요?

**Comment by paul2126** [comment]
민영님께서 다크모드 로직 바꿔주시면서 해결된 것으로 알고있고 몇번 테스트 해봐도 문제 없어서 닫겠습니다
