### ISSUE TITLE
게스트 나가기 버튼 활성화

### ISSUE THREAD

**Issue by paul2126** [snuhcs-course/swpp-2023-project-team-6#63]
현재 게스트모드 나가기 버튼이 아무런 동작을 하고있지 않습니다

**Comment by 89645321** [comment]
저는 로그인 후에 앱을 껐다 켜면 게스트 모드로 들어가지는데 그때 동작을 안 하는 걸로 확인했습니다. 혹시 게스트 모드로 들어간 후에 앱을 껐다 켜도 동작하지 않나요?

**Comment by paul2126** [comment]
> 저는 로그인 후에 앱을 껐다 켜면 게스트 모드로 들어가지는데 그때 동작을 안 하는 걸로 확인했습니다. 혹시 게스트 모드로 들어간 후에 앱을 껐다 켜도 동작하지 않나요?

로그인한 후 앱을 껐다 켜면 게스트 모드로 들어가는 것은 정상적인 작동이 아니고 나중에 고쳐지는 것으로 알고있어서 따로 대응은 안 했습니다.
그리고 말씀하신데로 로그인했다가 종료 후에 게스트모드로 들어간 상황에서 상징을 선택하면 죽는건 로그인 했을때의 커스텀 상징이나 개인 weight table이 안 맞아서 생기는 크래쉬일꺼에요
